modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/benjaminiserman/WingsContracts/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Wing's Contracts"
authors = "benjaminiserman"
description = '''
Reward automation with bulk-order contracts.
'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_for_forge_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
mandatory = false
versionRange = "[${create_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cc_tweaked"
mandatory = false
versionRange = "[${cc_tweaked_version}]"
ordering = "AFTER"
side = "BOTH"